version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # read from environment variable

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
